### ISSUE TITLE
Doesn't work with websockets

### ISSUE THREAD

**Issue by s1037989** [oetiker/mojolicious-plugin-reverseproxy#8]
What is necessary to get this to work with a Websocket app?  e.g. I'm using the Mojolicious example [chat.pl](https://github.com/mojolicious/mojo/blob/master/examples/chat.pl)

My `proxyfun` app is very simple:
```
use Mojolicious::Lite;
plugin 'ReverseProxy' => {
  destination_url => 'http+unix://%2Ftmp%2Fmojo.sock',
  req_processor => sub { 
    my ($c, $req) = @_;
    $req->url->path($c->tx->req->url->path);
  },
  res_processor => sub {
    my ($c, $res) = @_;
  },
};
app->start;
```
This seems to work pretty well for regular web pages, but doesn't seem to work at all for a Websocket connection.

**Comment by oetiker** [comment]
the problem is that for WebSockets you need a persistent connection which this mode of operation does not provide for ... here is an example for persistent connections https://github.com/oetiker/popruxi

I guess the solution would be to alter the code so that it detects opening WebSocket connections and then provides alternate hooks for this processing ... message by message or so
